// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "food-ordering-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// OrderDAO is an autogenerated mock type for the OrderDAO type
type OrderDAO struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, order
func (_m *OrderDAO) Create(ctx context.Context, order *domain.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrderItems provides a mock function with given fields: ctx, orderID
func (_m *OrderDAO) GetOrderItems(ctx context.Context, orderID string) ([]domain.OrderItem, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderItems")
	}

	var r0 []domain.OrderItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.OrderItem, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.OrderItem); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.OrderItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderDAO creates a new instance of OrderDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderDAO {
	mock := &OrderDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
