// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "food-ordering-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// OrderLogic is an autogenerated mock type for the OrderLogic type
type OrderLogic struct {
	mock.Mock
}

// PlaceOrder provides a mock function with given fields: ctx, req
func (_m *OrderLogic) PlaceOrder(ctx context.Context, req domain.OrderRequest) (*domain.Order, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.OrderRequest) (*domain.Order, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.OrderRequest) *domain.Order); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.OrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderLogic creates a new instance of OrderLogic. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderLogic(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderLogic {
	mock := &OrderLogic{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
